# Curated list of AI Security company domains for quick-access
CURATED_DOMAINS = [
    {"domain": "straiker.ai", "name": "Straiker"},
    {"domain": "repello.ai", "name": "Repello AI"},
    {"domain": "operant.ai", "name": "Operant AI"},
    {"domain": "prophetsecurity.ai", "name": "Prophet Security"},
    {"domain": "protectai.com", "name": "Protect AI"},
    {"domain": "hiddenlayer.com", "name": "HiddenLayer"},
    {"domain": "lasso.security", "name": "Lasso Security"},
    {"domain": "calypsoai.com", "name": "CalypsoAI"},
    {"domain": "robust-intelligence.com", "name": "Robust Intelligence"},
    {"domain": "armorblox.com", "name": "Armorblox"},
    {"domain": "pillar.security", "name": "Pillar Security"},
    {"domain": "zenity.io", "name": "Zenity"},
    {"domain": "lakera.ai", "name": "Lakera"},
    {"domain": "pangea.cloud", "name": "Pangea"},
    {"domain": "nightfall.ai", "name": "Nightfall AI"},
    {"domain": "aim.security", "name": "AIM Security"},
    {"domain": "aporia.com", "name": "Aporia"},
    {"domain": "prompt.security", "name": "Prompt Security"},
    {"domain": "invariantlabs.ai", "name": "Invariant Labs"},
    {"domain": "noma.security", "name": "Noma Security"},
    {"domain": "splxai.com", "name": "SPLX AI"},
    {"domain": "mindgard.ai", "name": "Mindgard"},
    {"domain": "cisco.com", "name": "Cisco"},
    {"domain": "paloaltonetworks.com", "name": "Palo Alto Networks"},
    {"domain": "crowdstrike.com", "name": "CrowdStrike"},
    {"domain": "sentinelone.com", "name": "SentinelOne"},
    {"domain": "wiz.io", "name": "Wiz"},
    {"domain": "snyk.io", "name": "Snyk"},
    {"domain": "datadog.com", "name": "Datadog"},
    {"domain": "elastic.co", "name": "Elastic"},
    {"domain": "openai.com", "name": "OpenAI"},
    {"domain": "anthropic.com", "name": "Anthropic"},
    {"domain": "langchain.dev", "name": "LangChain"},
    {"domain": "vercel.com", "name": "Vercel"},
    {"domain": "hashicorp.com", "name": "HashiCorp"},
]
